### ISSUE TITLE
This repo can now be archived

### ISSUE THREAD

**Issue by climbfuji** [JCSDA-internal/saber-data#51]
## Description

There was an update in SABER (https://github.com/JCSDA-internal/saber/pull/358) that allow us to archive this repository and remove it from the various bundles and CI scripts.

To do these updates in an organized way, it would be good to
- have a list of bundles that use `saber-data`
- have a list of repos that use `saber-data` in the CI
- in the bundle/repo PRs list the corresponding SABER PR that made saber-data redundant

[text heavily edited by Francois H to add mention of CI scripts]

## Requirements

Let's archive this repo after the bundles and scripts are updated.

Bundles to update:
- [x] jedi-bundle: https://github.com/JCSDA-internal/jedi-bundle/pull/21
- [x] fv3-bundle: https://github.com/JCSDA-internal/fv3-bundle/pull/95
- [x] ufs-bundle: https://github.com/JCSDA/ufs-bundle/pull/11
- [x] lfric-bundle: https://github.com/JCSDA-internal/lfric-bundle/pull/340
- [x] lfric-lite-bundle: https://github.com/JCSDA-internal/lfric-lite-bundle/pull/18
- [x] mpas-bundle: https://github.com/JCSDA-internal/mpas-bundle/pull/139
- [x] ufo-bundle: https://github.com/JCSDA-internal/ufo-bundle/pull/85
- [x] jopa-bundle: https://github.com/JCSDA-internal/jopa-bundle/pull/22
- [ ] ...

CI scripts to update:
- [x] fv3-jedi: https://github.com/JCSDA-internal/fv3-jedi/pull/696
- [ ] ...

## Acceptance Criteria (Definition of Done)

All bundles and CI scripts updated, this issue closed, repo archived

## Dependencies

All bundles and CI scripts updated (not strictly needed, but makes sense)

**Comment by shlyaeva** [comment]
If it's archived, would it still be available for people checking out previous bundle tags?

**Comment by climbfuji** [comment]
Yes, it just makes the entire repository read-only

**Comment by shlyaeva** [comment]
All of the repos/bundles/CI (at least the ones we're aware of) were updated; I think the repo can be archived now, and the issue closed.

**Comment by climbfuji** [comment]
I am going to close this issue and then archive the repo.
